README.md
pom.xml
src/main/java/com/github/lombrozo/jsmith/RandomJavaClass.java

Add the project description into `pom.xml` and `README.md`.
Closes: #7.
____
History:
- feat(#7): add description to pom.xml
- feat(#7): add project description into README

feat(#7): Add Project Description

---

.github/workflows/up.yaml

feat(#11): Update Version Automatically

---

.github/pull_request_template.md
.github/workflows/pdd.yml
CODE_OF_CONDUCT.md
README.md

Add CODE_OF_CONDUCT and PR template.
Closes: #25.
____
History:
- feat(#25): add a few sentences about 'How to Contribute'
- feat(#25): add code of conduct
- feat(#25): add PR template

feat(#25): Add CODE_OF_CONDUCT and PR template

---

.github/workflows/maven.test.yaml
README.md
pom.xml

In this PR I added a support of Java 8 for the plugin.
I added one more GitHub pipeline to check how the plugin works with Java 8

chore: Support Java 8

---

.github/workflows/maven.test.yaml
src/main/java/com/github/lombrozo/jsmith/antlr/rules/SeveralAttempts.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/SeveralAttemptsTest.java

In this PR I successfully fix the implementation of `SeveralAttempts` class. Now it works properly.
Fixes #98.
I added a few unit tests to cover the new implementation of `SeveralAttempts` class.

feat(#98): Fix `SeveralAttempts` Class Implementation

---

src/main/java/com/github/lombrozo/jsmith/antlr/Attributes.java
src/main/java/com/github/lombrozo/jsmith/antlr/semantic/TypeRule.java
src/main/java/com/github/lombrozo/jsmith/antlr/semantic/VariableUsage.java
src/main/java/com/github/lombrozo/jsmith/antlr/view/ErrorNode.java
src/main/java/com/github/lombrozo/jsmith/antlr/view/IntermediateNode.java
src/main/java/com/github/lombrozo/jsmith/antlr/view/Node.java
src/main/java/com/github/lombrozo/jsmith/antlr/view/TerminalNode.java

In this PR I make `Attributes` class immutable.
Closes #105.

feat(#105): Make `Attributes` Immutable

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/AntlrString.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/LexerCharSet.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/Literal.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/UnicodeString.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/AntlrStringTest.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/LiteralTest.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/UnicodeCharTest.java

In this PR I slightly refactored `UnicodeChar`, `LexerCharSet` and `Literal` classes. 
Also I introduced one more useful class `AntlrString` for simplicity.
Moreover, I added a few more tests for safety.
Closes: #84.

feat(#84): Create a Separate Class For `AntlrSting`

---

src/main/java/com/github/lombrozo/jsmith/guard/InMemoryCompiler.java
src/main/java/com/github/lombrozo/jsmith/guard/SyntaxGuard.java
src/test/java/com/github/lombrozo/jsmith/guard/InMemoryCompilerTest.java

In this PR I refactored `SyntaxGuard` significantly and added `InMemoryCompiler` to avoid reading files from filesystem for compilation.
Fixes #89 

feat(#89): SyntaxGuard Refactoring

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/ActionBlock.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/ActionBlockTest.java

Implemented ActionBlock class and covered it with tests

Implement ActionBlock rule

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/ActionScopeName.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/ActionScopeNameTest.java

Implemented ActionScopeName class.
PR for issue #88 

Implement ActionScopeName class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/ArgActionBlock.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/ActionScopeNameTest.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/ArgActionBlockTest.java

Implemented ArgActionBlock class.
PR for  #88

Implement ArgActionBlock class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/ElementOptions.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/ElementOptionsTest.java

Implemented elementOptions class and covered it with tests.
PR for #88 

Implement elementOptions class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/Ruleref.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/RulerefTest.java

Covered RuleRef with ArgActionBlock and ElementOption cases.
Fixes #86 

Cover RuleRef with more tests

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/Action.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/ActionTest.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/RulerefTest.java

Implemented action rule class and covered it with tests.
PR for #88

Implement action class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/DelegateGrammar.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/DelegateGrammarTest.java

Implemented delegateGrammar class and covered it with tests.
PR for #88 

Implement delegateGrammar class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/OptionValue.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/ActionTest.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/OptionValueTest.java

Implemented OptionValue class and covered it with tests.
PR for #88 

Implement OptionValue class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/LexerCommandExpr.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/LexerCommandExprTest.java

Implemented LexerCommandExpr class and covered it with test
PR for #88

Implement LexerCommandExpr class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/PredicateOption.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/PredicateOptionTest.java

Implemented PredicateOption class and covered it with tests.
PR for #88

Implement PredicateOption class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/BlockSet.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/BlockSetTest.java

Implemented BlockSet class and covered it with tests.
PR for #88 

Implement BlockSet class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/LexerCommand.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/LexerCommandTest.java

Implemented LexerCommand class and covered it with tests.
PR for #88 

Implement LexerCommand class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/LexerCommandName.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/LexerCommandNameTest.java

Implemented LexerCommandName class and covered it with tests.
PR for #88 

Implement LexerCommandName class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/DelegateGrammars.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/DelegateGrammarsTest.java

Implemented DelegateGrammars class and covered it with tests.
PR for #88 

Implement DelegateGrammars class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/LexerBlock.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/LexerBlockTest.java

Implemented LexerBlock class and covered it with tests.
PR for #88 

Implemented LexerBlock class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/LexerAlt.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/LexerAltTest.java

Implemented LexerAlt class and covered it with tests.
PR for #88 

Implement LexerAlt class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/PredicateOptions.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/PredicateOptionsTest.java

Implemented PredicateOptions class and covered it with tests.
PR for #88

Implement PredicateOptions class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/LexerCommands.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/LexerCommandsTest.java

Implemented LexerCommands class and covered it with tests.
PR for #88 

Implement LexerCommands class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/LabeledAlt.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/LabeledAltTest.java

Implemented LabeledAlt class and covered it with tests.

Implement LabeledAlt class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/Option.java
src/test/java/com/github/lombrozo/jsmith/antlr/rules/OptionTest.java

Implemented Option class and covered it with tests.
PR for #88

Implement Option class

---

src/main/java/com/github/lombrozo/jsmith/antlr/rules/BlockSet.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/DelegateGrammars.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/LabeledAlt.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/LexerAlt.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/LexerCommand.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/LexerCommands.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/Option.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/PredicateOption.java
src/main/java/com/github/lombrozo/jsmith/antlr/rules/PredicateOptions.java
src/main/java/com/github/lombrozo/jsmith/guard/Allowed.java
src/test/java/com/github/lombrozo/jsmith/guard/AllowedTest.java

Implemented Allowed class and covered it with tests.
PR for #173.

Implement Allowed class
